spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/listcery
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  freemarker:
    expose-request-attributes: true
  mvc.hiddenmethod.filter.enabled: true
  mail:
    host: smtp.yandex.ru
    username: ?
    password: ?
    port: 465
    protocol: smtps
    debug: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
